#UPDATING AND LINKING
SET SQL_SAFE_UPDATES=0;


#STOCKS
 ALTER TABLE STOCKS 
ADD CONSTRAINT FK_BOOKS_STOCK 
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) ON UPDATE CASCADE;
DELETE FROM STOCKS WHERE Book_id NOT IN (SELECT Book_id FROM BOOKS);
    
  #USERS AND USERS_LOCATION 
      ALTER TABLE Users
ADD PRIMARY KEY (User_id);
   ALTER TABLE USERS ADD COLUMN City VARCHAR(30);
   TRUNCATE TABLE USERS;
      UPDATE Users u
JOIN Users_Location l ON u.City = l.City
SET u.Location_Id = l.Location_ID;        #To include the location_id in the Users Table 
ALTER TABLE USERS DROP COLUMN City; 

		#RATINGS 
ALTER TABLE Ratings 
  ADD CONSTRAINT FK_BOOKS_RATINGS
  FOREIGN KEY(Book_id) REFERENCES BOOKS(Book_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
      DELETE FROM RATINGS WHERE Book_id NOT IN (SELECT Book_id FROM BOOKS);
      ALTER TABLE RATINGS MODIFY ISBN VARCHAR(25);
  
  
  #PUBLISHERS AND PUBLISHERS_LOCATION
       #lINKING P_location_Id To include the p_location_id in the publishders Table     
  ALTER TABLE PUBLISHERS
        ADD COLUMN P_LOCATION_ID INT; 
  
  UPDATE PUBLISHERS P
JOIN publishers_location k ON p.city = k.City
SET p.P_location_Id = k.P_Location_ID;
#MAKING P_location_Id AS FK 
ALTER TABLE PUBLISHERS 
ADD CONSTRAINT FK_PUBLISHERS_LOCATION_PUBLISHERS
FOREIGN KEY (P_LOCATION_ID) REFERENCES PUBLISHERS_LOCATION(P_LOCATION_ID);
ALTER TABLE PUBLISHERS DROP COLUMN City;

#Book_Format 
ALTER TABLE BOOK_FORMAT
CHANGE F_Id F_ID INT;


#BOOKS 
ALTER TABLE BOOKS 
ADD COLUMN F_ID INT,
ADD COLUMN A_ID INT,
ADD COLUMN P_ID INT;


	#making foreign keys 
    ALTER TABLE BOOKS 
    ADD CONSTRAINT FK_PUBLISHER_BOOK
    FOREIGN KEY (P_ID) REFERENCES PUBLISHERS(P_ID);
    
      ALTER TABLE BOOKS 
    ADD CONSTRAINT FK_AUTHORS_BOOK
    FOREIGN KEY (A_ID) REFERENCES AUTHORS(A_ID);
    
    ALTER TABLE BOOKS 
    ADD CONSTRAINT FK_BOOKFORMAT_BOOK
    FOREIGN KEY (F_ID) REFERENCES BOOK_FORMAT(F_ID);
    
     
     #linking foreign keys 
     UPDATE BOOKS b 
     JOIN AUTHORS a ON b.author_name=a.author_name
     SET b.A_ID = a.A_ID;
     
       UPDATE BOOKS b 
     JOIN book_format f ON b.format_type=f.format_type
     SET b.F_ID = f.F_ID;
     
     UPDATE BOOKS b 
     JOIN PUBLISHERS p ON b.publisher_name=p.publisher_name
     SET b.P_ID = p.P_ID;
     
	ALTER TABLE BOOKS DROP AUTHOR_NAME; 
    ALTER TABLE BOOKS DROP PUBLISHER_NAME; 
   ALTER TABLE BOOKS DROP  FORMAT_TYPE;
   ALTER TABLE BOOKS MODIFY A_ID INT AFTER PUBLICATION_YEAR;
   ALTER TABLE BOOKS MODIFY P_ID INT AFTER A_ID;
	ALTER TABLE BOOKS MODIFY F_ID INT AFTER P_ID;
	

ALTER TABLE STOCKS
DROP FOREIGN KEY FK_BOOKS_STOCK;

ALTER TABLE STOCKS
ADD CONSTRAINT FK_BOOKS_STOCK
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;


ALTER TABLE RATINGS
DROP FOREIGN KEY FK_BOOKS_RATINGS;

ALTER TABLE RATINGS
ADD CONSTRAINT FK_BOOKS_RATINGS
FOREIGN KEY (Book_id) REFERENCES BOOKS(Book_id)
ON DELETE CASCADE
ON UPDATE CASCADE;

DELETE FROM BOOKS WHERE Book_id >= 1007;


ALTER TABLE GENRES_AND_CATEGORIES
RENAME GENRES;
 
ALTER TABLE GENRES 
CHANGE COLUMN GENRES genre_name VARCHAR(50);

ALTER TABLE book_genres
ADD CONSTRAINT FK_book
FOREIGN KEY (Book_ID)
REFERENCES Books(Book_ID)
ON DELETE CASCADE;

ALTER TABLE book_genres
ADD CONSTRAINT FK_genre
FOREIGN KEY (Genre_ID)
REFERENCES genres(GENRE_ID)
ON DELETE CASCADE;

